import React from 'react';
import { TechPackItem } from '../types';

interface StandaloneDPPProps {
    data: {
        assetId: string;
        dpp: TechPackItem[];
    };
}

export default function StandaloneDPP({ data }: StandaloneDPPProps) {
    if (!data.dpp || data.dpp.length === 0) {
        return (
            <div className="min-h-screen bg-slate-900 text-slate-200 flex flex-col items-center justify-center p-8">
                <div className="bg-slate-800 p-8 rounded-xl border border-slate-700 max-w-lg w-full text-center">
                    <p className="text-slate-400">No Digital Product Passport data found.</p>
                </div>
            </div>
        );
    }

    return (
        <div className="min-h-screen bg-slate-950 text-slate-200 p-4 sm:p-8 flex justify-center font-sans tracking-wide">
            <div className="max-w-2xl w-full bg-slate-900 rounded-2xl border border-slate-800 shadow-2xl overflow-hidden shadow-indigo-900/10">
                
                <div className="bg-indigo-900/40 border-b border-indigo-500/20 p-6 flex flex-col items-center text-center">
                    <div className="w-16 h-16 bg-indigo-600 rounded-full flex items-center justify-center shadow-lg shadow-indigo-500/30 mb-4">
                        <svg xmlns="http://www.w3.org/2000/svg" className="h-8 w-8 text-white" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M3 10h18M7 15h1m4 0h1m-7 4h12a3 3 0 003-3V8a3 3 0 00-3-3H6a3 3 0 00-3 3v8a3 3 0 003 3z" />
                        </svg>
                    </div>
                    <h1 className="text-2xl font-black tracking-tight text-white uppercase">Digital Product Passport</h1>
                    <p className="text-indigo-200 text-sm mt-1 uppercase tracking-wider font-semibold">Verified Sustainability Profile</p>
                    <p className="text-slate-500 text-xs mt-2 font-mono">ID: {data.assetId}</p>
                </div>

                <div className="p-1">
                    {data.dpp.map((item, idx) => (
                        <div key={item.id || idx} className="p-5 border-b border-slate-800/50 flex flex-col sm:flex-row sm:items-center sm:justify-between hover:bg-slate-800/20 transition-colors">
                            <h3 className="text-sm font-bold text-slate-400 mb-1 sm:mb-0 w-1/3">{item.label}</h3>
                            <div className="text-sm font-medium text-slate-200 w-2/3 break-words sm:text-right">{item.value}</div>
                        </div>
                    ))}
                </div>

                <div className="p-6 bg-slate-950 border-t border-slate-800 text-center">
                    <p className="text-xs text-slate-600">This data represents a baseline estimate generated by AI analysis. It is intended for ideation and should be validated physically.</p>
                </div>
            </div>
        </div>
    );
}
